version: '3.3'

services:
  minikube:
    image: minikube:latest
    container_name: test-kuber
    restart: always
    network_mode: host
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
