apiVersion: v1
kind: Service
metadata:
  name: mongo-service 
spec:
  selector:
    app: mongo # label of pod
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017 # port of pod

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
  selector:
    app: mongo-express
  type: LoadBalancer # assign service an external IP
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30000 # port for external ip address, need to specific in browser to access service, must be 30000-32767
