{{- if .Values.configmap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mychart.fullname" . }}
data:
  {{- range $key, $val := .Values.configmap.data }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}